<WireGrid>:

    name: name
    email: email

    GridLayout:
        cols: 2
        size: root.width, root.height
        pos: 0, 0

        GridLayout:
            cols: 2

            Label:
                text: "Name:"

            TextInput:
                id: name
                multiline: False

            Label:
                text: "Email:"

            TextInput:
                id: email
                multiline: False